token = '709599068:AAFO9EwTK98FiKPNbWTaVfEbrfWvKHxyr0U'


class State:
    S_START = 0
    S_ENTER_TYPE_EXPENSE = 1
    S_ENTER_PRICE = 2
    S_ENTER_TYPE_INCOME = 3
    S_ENTER_INCOME = 4
    S_ENTER_BOARDCOST = 5
    S_ENTER_BOARDPRICE = 6
